import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=fileURLToPath(new URL('../',import.meta.url)),base=process.env.REACTIVE_URL||'http://127.0.0.1:8016';
await mkdir(root+'docs/reactive-review',{recursive:true});
const browser=await chromium.launch({channel:process.env.CI?undefined:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1080}}),errors=[],external=[];
page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>{if(!r.url().startsWith(base))external.push(r.url());});
await page.goto(base);await page.locator('#loading').waitFor({state:'hidden'});
let initial=await (await page.request.get(base+'/api/state')).json();
const reset=(request=page.request)=>request.post(base+'/api/reset',{headers:{'X-LN-Token':initial.token},data:{cells:120,seed:21,discard:true}});
await reset();await page.reload();await page.locator('#loading').waitFor({state:'hidden'});
assert.equal(await page.locator('#never').textContent(),'120');
await page.locator('#step').click();await page.waitForFunction(()=>document.querySelector('#clock').textContent==='0.2 h');
assert.equal(await page.locator('#decisions').textContent(),'0');
await page.screenshot({path:root+'docs/reactive-review/baseline.png',fullPage:true});
await page.locator('#prompt').fill('Create a germinal center and force all cells to differentiate');
await page.locator('#introduce').click();await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('Supported prompt'));
assert.equal(await page.locator('#population').textContent(),'120');
await page.locator('#prompt').fill('An antigen-bearing dendritic cell enters the lymph node.');
await page.locator('#introduce').click();await page.waitForFunction(()=>document.querySelector('#population').textContent==='121');
await page.locator('#play').click();
assert.match(await page.locator('#cellName').textContent(),/Dendritic/);
const arriving=await (await page.request.get(base+'/api/state')).json();
assert.equal(arriving.tissue.antigens.length,9);assert.equal(arriving.provider.requests,0);
await page.locator('#cellSelect').selectOption('LN-0001');
assert.match(await page.locator('#choice').textContent(),/never been asked/);
await page.locator('#cellSelect').selectOption('LN-0121');
await page.screenshot({path:root+'docs/reactive-review/arrival.png',fullPage:true});
await page.locator('#speed').selectOption('4');await page.locator('#play').click();
await page.waitForFunction(()=>Number(document.querySelector('#tissue').dataset.time)>=1440,{},{timeout:90000});
await page.locator('#play').click();
const after=await (await page.request.get(base+'/api/state')).json();
assert(after.tissue.metrics.antibodies>0);assert(after.tissue.metrics.never_queried>90);
assert.equal(after.provider.requests,0);assert.equal(after.tissue.metrics.antigen_accounted,9);
const dc=after.tissue.cells.find(c=>c.id==='LN-0121'),before=arriving.tissue.cells.find(c=>c.id==='LN-0121');
assert(Math.hypot(dc.x-before.x,dc.y-before.y)>10);
const plasmablast=after.tissue.cells.find(c=>c.state==='plasmablast');assert(plasmablast);
await page.locator('#cellSelect').selectOption(plasmablast.id);
await page.locator('#view').click();await page.screenshot({path:root+'docs/reactive-review/response.png',fullPage:true});
assert.match(await page.locator('#choice').textContent(),/local policy/);
const paused=await page.locator('#clock').textContent();await page.waitForTimeout(900);assert.equal(await page.locator('#clock').textContent(),paused);
await page.setViewportSize({width:390,height:844});await page.screenshot({path:root+'docs/reactive-review/mobile.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
const denied=await page.request.get(base+'/.env');assert.equal(denied.status(),404);
assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
await page.close();
const reduced=await browser.newPage({reducedMotion:'reduce',viewport:{width:1200,height:900}});
await reset(reduced.request);await reduced.goto(base);await reduced.locator('#loading').waitFor({state:'hidden'});
await reduced.locator('#introduce').click();await reduced.waitForFunction(()=>document.querySelector('#population').textContent==='121');
assert.equal(await reduced.locator('#play').getAttribute('aria-pressed'),'false');
await writeFile(root+'docs/reactive-review/checks.json',JSON.stringify({baseline_decisions:0,final:after.tissue.metrics,paid_requests:0,external_requests:external,errors,mobile_overflow:false,reduced_motion_autoplay:false},null,2));
console.log(JSON.stringify({metrics:after.tissue.metrics,errors,external}));
await browser.close();
