import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.REPLAY_URL||'http://127.0.0.1:8024/';
const browser=await chromium.launch({channel:process.env.CI?undefined:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1080}}),errors=[],requests=[];
await page.emulateMedia({reducedMotion:'reduce'});
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push({url:r.url(),method:r.method()}));
page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});
await page.goto(base);await page.locator('#loading').waitFor({state:'hidden',timeout:60000});
assert.equal(await page.locator('#play').isEnabled(),true);
await page.getByRole('button',{name:/First division ·/}).click();
assert(Number(await page.locator('#divisions').textContent())>0);
assert.match(await page.locator('#cellIdentity').textContent(),/parent LN-/);
await page.getByRole('button',{name:/First IgM ·/}).click();
assert(Number(await page.locator('#antibodies').textContent())>0);
assert.match(await page.locator('#choice').textContent(),/Jev/);
await page.getByRole('button',{name:/GC formed ·/}).click();
const t=await page.locator('#tissue').getAttribute('data-time');
await page.locator('#play').click();await page.waitForFunction(t=>document.querySelector('#tissue').dataset.time!==t,t);await page.locator('#play').click();
await page.getByRole('button',{name:/First division ·/}).click();
await mkdir('docs/recording-review',{recursive:true});
await page.screenshot({path:'docs/recording-review/division.png',fullPage:true});
await page.getByRole('button',{name:/Plasma cell ·/}).click();
const camera=()=>page.locator('#tissue').evaluate(async el=>{await new Promise(requestAnimationFrame);return {x:+el.dataset.cameraX,y:+el.dataset.cameraY,zoom:+el.dataset.cameraZoom};});
const cameraNear=async expected=>page.waitForFunction(expected=>{
 const d=document.querySelector('#tissue').dataset;
 return Object.entries(expected).every(([key,value])=>Math.abs(+d['camera'+key[0].toUpperCase()+key.slice(1)]-value)<.02);
},expected);
await page.locator('#zoom').fill('4');await cameraNear({zoom:4});
const focused=await camera();
await page.locator('#panLeft').click();await page.waitForFunction(x=>+document.querySelector('#tissue').dataset.cameraX<x,focused.x);
await page.locator('#panRight').click();await cameraNear({x:focused.x});
await page.locator('#panUp').click();await page.waitForFunction(y=>+document.querySelector('#tissue').dataset.cameraY>y,focused.y);
await page.locator('#panDown').click();await cameraNear({y:focused.y});
await page.locator('#zoomOut').click();await cameraNear({zoom:3.2});
await page.locator('#zoomIn').click();await cameraNear({zoom:4});
await page.locator('#zoom').fill('6');await cameraNear({zoom:6});assert(await page.locator('#zoomIn').isDisabled());
await page.locator('#resetView').click();await cameraNear({x:0,y:0,zoom:1});assert(await page.locator('#zoomOut').isDisabled());
await page.locator('#zoom').fill('4');await cameraNear({zoom:4});
await page.locator('#tissue').scrollIntoViewIfNeeded();
let box=await page.locator('#tissue').boundingBox();
const identity=await page.locator('#cellIdentity').textContent();
await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();
await page.mouse.move(box.x+box.width/2+100,box.y+box.height/2+40,{steps:8});await page.mouse.up();
const dragged=await camera();assert(dragged.x<0&&dragged.y>0,'Dragging moves the tissue in both axes');
assert.equal(await page.locator('#cellIdentity').textContent(),identity,'Dragging does not select a different cell');
await page.mouse.move(box.x+box.width/2,box.y+box.height/2+5);await page.mouse.wheel(0,-100);
await page.waitForFunction(()=>+document.querySelector('#tissue').dataset.cameraZoom>4.8);
const wheeled=await camera();assert(Math.hypot(wheeled.x-dragged.x,wheeled.y-dragged.y)<.5,'Zoom at the center keeps the same tissue location');
await page.locator('#tissue').press('Home');await cameraNear({x:0,y:0,zoom:1});
await page.locator('#tissue').press('+');await cameraNear({zoom:1.25});
await page.locator('#tissue').press('ArrowRight');await page.waitForFunction(()=>+document.querySelector('#tissue').dataset.cameraX>0);
const manual=await camera(),frame=await page.locator('#tissue').getAttribute('data-time');
await page.locator('#play').click();await page.waitForFunction(t=>document.querySelector('#tissue').dataset.time!==t,frame);await page.locator('#play').click();
await cameraNear(manual);
await page.locator('#seek').fill('1000');await page.locator('#seek').dispatchEvent('input');await cameraNear(manual);
await page.getByRole('button',{name:/Plasma cell ·/}).click();await cameraNear({zoom:1.85});
await page.locator('#zoom').fill('4');await cameraNear({zoom:4});
await page.screenshot({path:'docs/recording-review/plasma.png',fullPage:true});
await page.getByRole('button',{name:/Failed selection ·/}).click();
assert.match(await page.locator('#cellStatus').textContent(),/apoptosis/);
await page.locator('#lastFrame').click();
assert.equal(await page.locator('#replayWindow').inputValue(),'full');
const manifest=await (await page.request.get(new URL('recording.json',base).href)).json();
assert.equal(Number(await page.locator('#antibodies').textContent()),manifest.metrics.antibodies);
assert.equal(Number(await page.locator('#population').textContent()),manifest.metrics.live);
assert.equal(Number(await page.locator('#divisions').textContent()),manifest.metrics.net_births);
await page.screenshot({path:'docs/recording-review/final.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.locator('#resetView').click();await cameraNear({x:0,y:0,zoom:1});
await page.locator('#zoom').fill('2');await cameraNear({zoom:2});
await page.locator('#tissue').scrollIntoViewIfNeeded();box=await page.locator('#tissue').boundingBox();
const touch=await page.context().newCDPSession(page),cx=box.x+box.width/2,cy=box.y+box.height/2;
await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx-30,y:cy,id:1},{x:cx+30,y:cy,id:2}]});
await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cx-60,y:cy,id:1},{x:cx+60,y:cy,id:2}]});
await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
await cameraNear({zoom:4});
const pinched=await camera();
await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx,y:cy,id:1}]});
await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cx+40,y:cy+20,id:1}]});
await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
const touchPan=await camera();assert(touchPan.x<pinched.x&&touchPan.y>pinched.y,'One finger pans after a pinch');
await touch.detach();
await page.locator('#resetView').click();await cameraNear({x:0,y:0,zoom:1});
await page.screenshot({path:'docs/recording-review/mobile.png',fullPage:true});
const before=requests.length;await page.locator('#play').click();await page.waitForTimeout(400);await page.locator('#play').click();
assert.equal(requests.length,before,'Playback must not fetch new decisions');
assert.match(await page.locator('#play').textContent(),/Play/);
const forbidden=requests.filter(r=>r.method!=='GET'||new URL(r.url).origin!==new URL(base).origin||/\/api\//.test(r.url));
assert.deepEqual(errors,[]);assert.deepEqual(forbidden,[]);
console.log({division:true,plasma:true,IgM:true,playback:true,seek:true,zoom:true,pan:true,drag:true,pinch:true,keyboard:true,cameraPersists:true,mobileOverflow:false,errors,forbidden});
await browser.close();
