const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));
const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1512,height:982}});const errors=[],writes=[];
page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>{if(r.method()==='POST')writes.push(r.url());});
await page.goto('http://127.0.0.1:8010/?recording=231bd6719cad444a8d0d');await page.locator('#replay').waitFor({state:'visible',timeout:60000});
if(!(await page.locator('#providerBadge').textContent()).includes('Jev · recorded'))throw Error('Wrong provider');
await page.getByRole('button',{name:'Memory B · 63.0 h',exact:true}).click();
if(await page.locator('#metricMemory').textContent()!=='3')throw Error('Memory milestone mismatch');
await page.getByRole('button',{name:'First division · 64.0 h',exact:true}).click();
if(await page.locator('#metricDivisions').textContent()!=='1')throw Error('Division milestone mismatch');
if(await page.locator('#metricLive').textContent()!=='99')throw Error('Cell accounting mismatch');
if(!(await page.locator('#policyNote').isVisible()))throw Error('Missing proposed policy disclosure');
if(await page.getByRole('button',{name:/^Plasma cell/}).count())throw Error('Invented plasma milestone');
await page.evaluate(()=>{document.activeElement?.blur();window.scrollTo(0,0);});await page.screenshot({path:root+'docs/jev-demo-final.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.screenshot({path:root+'docs/jev-demo-mobile.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
console.log({time:await page.locator('#time').textContent(),milestones:await page.locator('#milestones').textContent(),memory:await page.locator('#metricMemory').textContent(),divisions:await page.locator('#metricDivisions').textContent(),writes,errors});
if(writes.length||errors.length)throw Error('Playback made mutations or had errors');await browser.close();
