const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
import {mkdir} from 'node:fs/promises';
const base=process.env.SITE_URL||'http://127.0.0.1:8020/';
const browser=await chromium.launch({channel:process.env.CI?undefined:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1512,height:982}});const errors=[],requests=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push({url:r.url(),method:r.method()}));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});
await page.goto(base);await page.locator('#loading').waitFor({state:'hidden',timeout:60000});
await page.getByRole('button',{name:'Memory B · 63.0 h',exact:true}).click();
if(await page.locator('#metricMemory').textContent()!=='3')throw Error('Memory mismatch');
await page.getByRole('button',{name:'First division · 64.0 h',exact:true}).click();
if(await page.locator('#metricDivisions').textContent()!=='1'||await page.locator('#metricLive').textContent()!=='99')throw Error('Division/accounting mismatch');
if(!(await page.locator('#policyNote').isVisible()))throw Error('Missing model-policy disclosure');
await mkdir('/tmp/ln-static-qa',{recursive:true});await page.locator('#viewport').screenshot({path:'/tmp/ln-static-qa/tissue.png'});await page.screenshot({path:'/tmp/ln-static-qa/desktop.png',fullPage:true});
await page.getByRole('button',{name:'GC formed · 22.5 h',exact:true}).click();await page.locator('#play').click();await page.waitForTimeout(450);await page.locator('#play').click();
if(await page.locator('#time').textContent()==='22.5 h')throw Error('Playback did not advance');
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/ln-static-qa/mobile.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
await page.goto(new URL('model.html',base).href);if(!(await page.textContent('body')).includes('No plasma cells'))throw Error('Missing provenance page');
await page.goto(new URL('?recording=https://example.com/evil.gz',base).href);await page.waitForFunction(()=>document.querySelector('#loading').textContent.includes('not in the public catalog'));
const forbidden=requests.filter(r=>r.method!=='GET'||new URL(r.url).origin!==new URL(base).origin||/\/api\//.test(r.url));
console.log({base,requests:requests.length,errors,forbidden,memory:3,divisions:1,externalCatalogRejected:true});
if(errors.length||forbidden.length)throw Error('Static site made unexpected requests or errors');await browser.close();
