const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
import {mkdir,readFile} from 'node:fs/promises';
import {gunzipSync} from 'node:zlib';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const qa=join(tmpdir(),'ln-static-qa');
const base=process.env.SITE_URL||'http://127.0.0.1:8020/';
const browser=await chromium.launch({channel:process.env.CI?undefined:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1512,height:982}});const errors=[],requests=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push({url:r.url(),method:r.method()}));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});
await page.goto(base);await page.locator('#loading').waitFor({state:'hidden',timeout:60000});
await page.waitForFunction(()=>document.querySelector('#illustrated').getAttribute('aria-pressed')==='true');
await page.getByRole('button',{name:'Memory B · 63.0 h',exact:true}).click();
if(await page.locator('#metricMemory').textContent()!=='3')throw Error('Memory mismatch');
await page.getByRole('button',{name:'First division · 64.0 h',exact:true}).click();
if(await page.locator('#metricDivisions').textContent()!=='1'||await page.locator('#metricLive').textContent()!=='99')throw Error('Division/accounting mismatch');
if(!(await page.locator('#policyNote').isVisible()))throw Error('Missing model-policy disclosure');
await mkdir(qa,{recursive:true});await page.locator('#viewport').screenshot({path:join(qa,'tissue.png')});await page.screenshot({path:join(qa,'desktop.png'),fullPage:true});
await page.getByRole('button',{name:'GC formed · 22.5 h',exact:true}).click();
await page.locator('#top').click();
await page.locator('#scene').scrollIntoViewIfNeeded();
const episode=JSON.parse(gunzipSync(await readFile(new URL('../recordings/examples/lymph-node-memory.ln.json.gz',import.meta.url))));
const frame=episode.frames.find(f=>f.time_min===22.5*60),bounds=await page.locator('#scene').boundingBox();
const scale=bounds.height/(2*470*Math.tan(39*Math.PI/360))*150/episode.final.params.radius_um;
for(const kind of ['B','CD4','DC']){
 const cell=frame.cells.find(c=>c.kind===kind);
 await page.mouse.click(bounds.x+bounds.width/2+cell.x*scale,bounds.y+bounds.height/2-cell.y*scale);
 const label=await page.locator('#cellAction').innerText();
 if(!label.includes(cell.id)||!label.includes('Jev:'))throw Error('Recorded agent selection lost its Jev identity');
}
await page.screenshot({path:join(qa,'recorded-agent.png'),fullPage:true});
await page.locator('#play').click();await page.waitForTimeout(450);await page.locator('#play').click();
if(await page.locator('#time').textContent()==='22.5 h')throw Error('Playback did not advance');
await page.setViewportSize({width:390,height:844});await page.screenshot({path:join(qa,'mobile.png'),fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
await page.goto(new URL('model.html',base).href);if(!(await page.textContent('body')).includes('No plasma cells'))throw Error('Missing provenance page');
await page.goto(new URL('?recording=https://example.com/evil.gz',base).href);await page.waitForFunction(()=>document.querySelector('#loading').textContent.includes('not in the public catalog'));
const forbidden=requests.filter(r=>r.method!=='GET'||new URL(r.url).origin!==new URL(base).origin||/\/api\//.test(r.url));
console.log({base,requests:requests.length,errors,forbidden,memory:3,divisions:1,externalCatalogRejected:true});
if(errors.length||forbidden.length)throw Error('Static site made unexpected requests or errors');await browser.close();
